#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
#### SYSCTL START ####
- name: Enable IPv4 routing in the kernel
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
  tags:
    - kube_node_installation
#### SYSCTL END ####

#### IPTABLES START ####
- name: Disable iptables
  service: name=iptables enabled=no state=stopped
  when: enable_kube_host_iptables == "0"
  tags:
    - kube_node_installation

- name: Update iptables required ports
  template: 
    src: "templates/misc/kube_node-iptables.j2"
    dest: "{{ iptables_rules_script }}"
    owner: root
    group: root
    mode: 0744
  when: enable_kube_host_iptables == "1"
  tags:
    - kube_node_installation

- name: Push iptables update
  shell: "{{ iptables_rules_script }}"
  when: enable_kube_host_iptables == "1"
  tags:
    - kube_node_installation

- name: Restart iptables
  service: name=iptables state=restarted
  when: enable_kube_host_iptables == "1"
  tags:
    - kube_node_installation
#### IPTABLES START ####

#### CLEANUP START ####
# This cleans up any existing implementations and resets for flannel
- name: Remove docker0 bridge if it exists
  command: "{{ item }}"
  ignore_errors: true
  with_items:
    - /usr/sbin/ifconfig docker0 down
    - /usr/sbin/brctl delbr docker0
  tags:
    - kube_node_installation
#### CLEANUP END ####

#### FLANNEL START ####
- name: Install flannel
  yum:  name={{ flannel_pkg }} state=present
  # use_pkg_mgr_for_flannel called out in photon_kube.yml playbook
  when: not install_flannel_from_src
  tags:
    - packages
    - kube_master_installation
    
- name: Download flannel binary from Github
  get_url:
    url: "{{ flannel_src_dl_url }}"
    dest: /usr/bin/flanneld
    owner: root
    group: root
    mode: 0755    
  # use_pkg_mgr_for_flannel called out in photon_kube.yml playbook    
  when: install_flannel_from_src
  tags:
    - packages
    - kube_master_installation

- name: Install flannel service unit
  template:
    src: "templates/systemd/flannel.service.j2"
    dest: "{{ flannel_svc_unit }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - kube_node_installation

- name: Reload flannel's systemd config
  command: systemctl daemon-reload
  tags:
    - kube_node_installation

- name: Start flannel service
  service: name=flannel enabled=yes state=restarted
  tags:
    - kube_node_installation
#### FLANNEL END ####

#### DOCKER START ####
- name: Install docker
  yum:  name={{ docker_package }} state=present
  tags:
    - packages
    - kube_node_installation

- name: Install docker service unit
  template:
    src: "templates/systemd/docker.service.j2"
    dest: "{{ docker_service_unit }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - kube_node_installation

- name: Reload docker's systemd config
  command: systemctl daemon-reload
  tags:
    - kube_node_installation

- name: Start docker service
  service: name=docker enabled=yes state=restarted
  tags:
    - kube_node_installation
#### DOCKER END ####

#### KUBERNETES MINION START ####
- name: Install kubernetes from package manager
  yum:  name={{ kubernetes_package }} state=present
  when: install_kube_from_src == "0"
  tags:
    - packages
    - kube_node_installation

- name: Check for existing Kubernetes installation archive
  stat:
    path: "{{ kube_src_local_parent_dir }}/{{ kube_src_local_parent_archive }}"
  when: install_kube_from_src == "1"
  register: kube_existing_src
  tags:
    - kube_node_installation

- name: Download the Kubernets binaries
  get_url:
    url: "{{ kube_src_dl_url }}"
    dest: "{{ kube_src_local_parent_dir }}/{{ kube_src_local_parent_archive }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644
    tmp_dest: "{{ kube_src_local_parent_dir }}"    
  when: (install_kube_from_src == "1") and (not kube_existing_src.stat.exists)
  tags:
    - kube_node_installation
    
- name: Unarchive existing kubernetes parent binary
  unarchive:
    src: "{{ kube_src_local_parent_dir }}/{{ kube_src_local_parent_archive }}"
    dest: "{{ kube_src_local_parent_dir }}"
    owner: "{{ ansible_ssh_user }}"
    group:  "{{ ansible_ssh_user }}"
    copy: no
  when: install_kube_from_src == "1"
  tags:
    - kube_node_installation

- name: Unarchive individual kube service binaries
  unarchive:
    src: "{{ kube_src_local_child_dir }}/{{ kube_src_local_child_archive }}"
    dest: "{{ kube_src_local_child_dir }}"
    copy: no
  when: install_kube_from_src == "1"
  tags:
    - kube_node_installation
    
- name: Install kube minion binaries
  copy: 
    src: "{{ kube_src_local_bin_dir }}/{{ item }}"
    dest: "{{ kube_bin_local_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
    remote_src: True
  with_items:
    - kubelet
    - kube-proxy
    - kubectl
  when: install_kube_from_src == "1"
  tags:
    - kube_node_installation    

- name: Create kube group
  group:
    name: kube
    state: present
  when: install_kube_from_src == "1"
  tags:
    - kube_node_installation

- name: Create kube user
  user:
    name: kube
    createhome: no
    group: kube
    state: present
  when: install_kube_from_src == "1"
  tags:
    - kube_node_installation

- name: Create kube config and working directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  when: install_kube_from_src == "1"
  with_items:
    - "{{ kube_cfg_dir }}"
    - "{{ kubelet_working_dir }}"
  tags:
    - kube_node_installation

- name: Install kubelet and kube-proxy configs
  template:
    src: "templates/configs/{{ item }}.j2"
    dest: "{{ kube_cfg_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - config
    - kubelet
  tags:
    - kube_node_installation

- name: Install the kube minion systemd services
  template:
    src: "templates/systemd/{{ item.name }}.service.j2"
    dest: "{{ item.svc }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { name: "kube-proxy", svc: "/etc/systemd/system/kube-proxy.service" }
    - { name: "kubelet", svc: "/etc/systemd/system/kubelet.service" }  
  when: install_kube_from_src == "1"
  tags:
    - kube_node_installation

- name: Start kube-proxy and kubelet
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - kube-proxy
    - kubelet
  tags:
    - kube_node_installation

# kubelet sometimes fails after startup, not sure why. Sleep for 5
# and then start kubelet again
- name: Sleep 5 seconds
  pause: seconds=5
  tags:
    - kube_node_installation
    
- name: Start kubelet
  service: name=kubelet enabled=yes state=started
  tags:
    - kube_node_installation
#### KUBERNETES MINION END ####
