---
- name: test for kubernetes installed
  command: rpm -q kubernetes
  register: kubernetes_installed
  ignore_errors: yes

- name: install kubernetes
  yum:  name={{ kubernetes_package }} state=present
  when: kubernetes_installed.rc == 1

- name: Set up configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ kube_config_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - config
    - kubelet
  notify:
    - restart kubelet
    - restart kube-proxy

- name: Set up services
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - flannel.service
    - docker.service

- name: reload systemd
  shell: systemctl daemon-reload

- name: start services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - kubelet
    - kube-proxy
    - docker
    - flannel

- name: test for flannel installed
  command: rpm -q flannel
  register: flannel_installed
  ignore_errors: yes

- name: install flannel
  yum:  name={{ flannel_package }} state=present
  when: flannel_installed.rc == 1
